# Generated by Django 5.2.17 on 2026-09-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='catalog_pro_categor_50f92a_idx'), models.Index(fields=['name'], name='catalog_pro_name_f603c0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('sku',), name='product_unique_active_sku'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='product_name_not_empty'), models.CheckConstraint(condition=models.Q(('sku', ''), _negated=True), name='product_sku_not_empty'), models.CheckConstraint(condition=models.Q(('category', ''), _negated=True), name='product_category_not_empty'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='product_price_not_negative'), models.CheckConstraint(condition=models.Q(('weight_kg__isnull', True), ('weight_kg__gte', 0), _connector='OR'), name='product_weight_not_negative')],
            },
        ),
    ]
